# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c05c36ad61980f885314be18d9cfe3198be9244e1370b9702d088ce329638dbbf18aec20aa90d321b4a9c0d812e95d836fdb99b89b6f8af82e838e5b572abe0

test:
  secret_key_base: 58c7969935e343e87b1415f5c32a37158290c194cb33aa5cc79cc79e26b58e6d24bf25ad715034df369e6056c02ca8a830211d00dda3f7941e53ecfcb84473f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
